# config.yaml

# Custom settings
project: runs  # Directory to save results
task: detect   # Task type (e.g., detect, segment, classify)
model: best.pt  # Path to model
conf: 0.25  # Confidence threshold
iou: 0.45   # IoU threshold
imgsz: 640  # Image size
source: 0   # Webcam as source (0 for default webcam)
name: thesis  # Experiment name

# Include all fields from default.yaml
mode: predict  # YOLO mode, i.e. train, val, predict, export, track, benchmark
data: coco.yaml
# Train settings
epochs: 100
patience: 100
batch: 16
save: True
save_period: -1
cache: False
device:  # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8
exist_ok: False
pretrained: True
optimizer: auto
verbose: True
seed: 0
deterministic: True
single_cls: False
rect: False
cos_lr: False
close_mosaic: 10
resume: False
amp: True
fraction: 1.0
profile: False
freeze: None
multi_scale: False

# Segmentation
overlap_mask: True
mask_ratio: 4

# Classification
dropout: 0.0

# Val/Test settings
val: True
split: val
save_json: False
save_hybrid: False
max_det: 300
half: False
dnn: False
plots: True

# Predict settings
vid_stride: 1
stream_buffer: False
visualize: False
augment: False
agnostic_nms: False
classes:  # (int | list[int], optional) filter results by class, i.e. classes=0, or classes=[0,2,3]
retina_masks: False
embed:  # (list[int], optional) return feature vectors/embeddings from given layers

# Visualize settings
show: False
save_frames: False
save_txt: False
save_conf: False
save_crop: False
show_labels: True
show_conf: True
show_boxes: True
line_thickness: 0.5  # (int, optional) line width of the bounding boxes. Scaled to image size if None.

# Export settings
format: torchscript
keras: False
optimize: False
int8: False
dynamic: False
simplify: True
opset:  # (int, optional) ONNX: opset version
workspace: 4.0  # (float, optional) TensorRT: workspace size (GiB), `None` will let TensorRT auto-allocate memory
nms: False

# Hyperparameters
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
copy_paste_mode: "flip"
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0

# Tracker settings
tracker: botsort.yaml  # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]